version: '3.9'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
  logstash:
    build: ./logstash
    ports:
      - "9600:9600"
      - "5044:5044"
